version: "3.8"

services:
  db-postgres-server:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
