version: "3.8"

services:
  db-postgres-server:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  back-end:
    build:
        context: ./BackEnd
        dockerfile: Dockerfile
    ports:
        - "5042:8080"
    depends_on:
        - db-postgres-server
    command: sh -c "sleep 2 && dotnet Infrastructure.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker