version: "3.8"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Testzdz2024"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
  back-end:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "5042:8080"
    depends_on:
      - sqlserver
    command: sh -c "sleep 7 && dotnet Infrastructure.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  front-end:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - back-end
